"use client";
import { Geist, Geist_Mono } from "next/font/google";
import {
    HeroUIProvider,
    Navbar,
    NavbarBrand,
    NavbarContent,
    NavbarItem,
    Link,
    Button
} from '@heroui/react'; // Importing components from heroui/react
import "../../src/input.css"
import "../../src/output.css"
import "./globals.css"
import {AcmeLogo} from "@/app/page";
import Header from "@/components/Header/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
/*
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};*/

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <head></head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
      <HeroUIProvider>
         <Header/>
          <main>
              {children}
          </main>
      </HeroUIProvider>

      </body>
    </html>
  );
}
