"use client";
import { Geist, Geist_Mono } from "next/font/google";
import {
    HeroUIProvider,
    Navbar,
    NavbarBrand,
    NavbarContent,
    NavbarItem,
    Link,
    Button
} from '@heroui/react'; // Importing components from heroui/react
import "../../src/input.css"
import "../../src/output.css"
import "./globals.css"
import {AcmeLogo} from "@/app/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
/*
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};*/

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <head></head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
      <HeroUIProvider>
          <Navbar shouldHideOnScroll>
              <NavbarBrand>
                  <AcmeLogo />
                  <p className="font-bold text-inherit">ACME</p>
              </NavbarBrand>
              <NavbarContent className="sm:flex gap-4" justify="center">
                  <NavbarItem>
                      <Link color="foreground" href="#">
                          Features
                      </Link>
                  </NavbarItem>
                  <NavbarItem>
                      <Link aria-current="page" href="#">
                          Customers
                      </Link>
                  </NavbarItem>
                  <NavbarItem>
                      <Link color="foreground" href="#">
                          Integrations
                      </Link>
                  </NavbarItem>
              </NavbarContent>
              <NavbarContent justify="end">
                  <NavbarItem className="lg:flex">
                      <Link href="#">Login</Link>
                  </NavbarItem>
                  <NavbarItem>
                      <Button as={Link} color="primary" href="#" variant="flat">
                          Sign Up
                      </Button>
                  </NavbarItem>
              </NavbarContent>
          </Navbar>
          <main>
              {children}
          </main>
      </HeroUIProvider>

      </body>
    </html>
  );
}
